INSERT INTO dmstemplate.template (template_id,
                                  process_id,
                                  template_name,
                                  template_type,
                                  approved_by,
                                  modified_by,
                                  modified_on,
                                  template_fields,
                                  template_stamp,
                                  template_data,
                                  is_active,
                                  version,
                                  created_by,
                                  created_on) VALUES
('414846b4-ec59-497e-9e28-bcc7d7ac678c',
 'DMS-P',
 'WelcomeLetter1',
 'DOCX',
 'Anton',
 'Anton',
 '2021-10-08',
 '[{"fieldName": "Name", "fieldType": "STRING", "isRequired": true, "defaultValue": "123"}]',
 null,
 null,
 true,
 2,
 'Anton',
 '2021-10-08');

INSERT INTO dmstemplate.template_history (audit_id,
                                          template_id,
                                          process_id,
                                          template_name,
                                          template_type,
                                          approved_by,
                                          modified_by,
                                          modified_on,
                                          template_fields,
                                          template_stamp,
                                          template_data,
                                          is_active,
                                          version,
                                          created_by,
                                          created_on )
VALUES ('0d8dfa28-4870-11ec-81d3-0242ac130003',
        '414846b4-ec59-497e-9e28-bcc7d7ac678c',
        'OLD_PROCESS_NAME',
        'WelcomeLetter1',
        'DOCX',
        'Anton',
        'Anton',
        '2021-10-08',
        '[{"fieldName": "Name", "fieldType": "STRING", "isRequired": true, "defaultValue": "123"}]',
        null,
        null,
        true,
        1,
        'Anton',
        '2021-10-08');

INSERT INTO dmstemplate.template_history (audit_id,
                                          template_id,
                                          process_id,
                                          template_name,
                                          template_type,
                                          approved_by,
                                          modified_by,
                                          modified_on,
                                          template_fields,
                                          template_stamp,
                                          template_data,
                                          is_active,
                                          version,
                                          created_by,
                                          created_on )
VALUES ('d3516946-486d-11ec-81d3-0242ac130003',
        '414846b4-ec59-497e-9e28-bcc7d7ac678c',
        'DMS-P',
        'WelcomeLetter1',
        'DOCX',
        'Anton',
        'Anton',
        '2021-10-08',
        '[{"fieldName": "Name", "fieldType": "STRING", "isRequired": true, "defaultValue": "123"}]',
        null,
        null,
        true,
        2,
        'Anton',
        '2021-10-08');


INSERT INTO dmstemplate.template (template_id,
                                  process_id,
                                  template_name,
                                  template_type,
                                  approved_by,
                                  modified_by,
                                  modified_on,
                                  template_fields,
                                  template_stamp,
                                  template_data,
                                  is_active,
                                  version,
                                  created_by,
                                  created_on) VALUES
('9234af48-5f0c-4d1e-a6c7-903e18e03df1',
 'DMS-P',
 'WelcomeLetter2',
 'DOCX',
 'Anton',
 'Anton',
 '2021-10-08',
 '[{"fieldName": "Name", "fieldType": "STRING", "isRequired": true, "defaultValue": "123"}]',
 null,
 null,
 true,
 1,
 'Anton',
 '2021-10-08');

INSERT INTO dmstemplate.template_history (audit_id,
                                          template_id,
                                          process_id,
                                          template_name,
                                          template_type,
                                          approved_by,
                                          modified_by,
                                          modified_on,
                                          template_fields,
                                          template_stamp,
                                          template_data,
                                          is_active,
                                          version,
                                          created_by,
                                          created_on )
VALUES ('ba32cdec-486d-11ec-81d3-0242ac130003',
        '9234af48-5f0c-4d1e-a6c7-903e18e03df1',
        'DMS-P',
        'WelcomeLetter2',
        'DOCX',
        'Anton',
        'Anton',
        '2021-10-08',
        '[{"fieldName": "Name", "fieldType": "STRING", "isRequired": true, "defaultValue": "123"}]',
        null,
        null,
        true,
        1,
        'Anton',
        '2021-10-08');

INSERT INTO dmstemplate.template (template_id,
                                  process_id,
                                  template_name,
                                  template_type,
                                  approved_by,
                                  modified_by,
                                  modified_on,
                                  template_fields,
                                  template_stamp,
                                  template_data,
                                  is_active,
                                  version,
                                  created_by,
                                  created_on) VALUES
('ff055243-5ceb-42c0-adca-634ebc484db4',
 'TEST_PROCESS',
 'WelcomeLetter3',
 'DOCX',
 'Sameer',
 'donna-service-user',
 '2021-10-12',
 '[{"fieldName": "Name", "fieldType": "STRING", "isRequired": true, "defaultValue": "123"}]',
 null,
 null,
 true,
 1,
 'Anton',
 '2021-10-08');

INSERT INTO dmstemplate.template_history (audit_id,
                                          template_id,
                                          process_id,
                                          template_name,
                                          template_type,
                                          approved_by,
                                          modified_by,
                                          modified_on,
                                          template_fields,
                                          template_stamp,
                                          template_data,
                                          is_active,
                                          version,
                                          created_by,
                                          created_on )
VALUES ('a4d9d97c-486d-11ec-81d3-0242ac130003',
        'ff055243-5ceb-42c0-adca-634ebc484db4',
        'TEST_PROCESS',
        'WelcomeLetter3',
        'DOCX',
        'Sameer',
        'donna-service-user',
        '2021-10-12',
        '[{"fieldName": "Name", "fieldType": "STRING", "isRequired": true, "defaultValue": "123"}]',
        null,
        null,
        true,
        1,
        'Anton',
        '2021-10-08');

INSERT INTO dmstemplate.template (template_id,
                                  process_id,
                                  template_name,
                                  template_type,
                                  approved_by,
                                  modified_by,
                                  modified_on,
                                  template_fields,
                                  template_stamp,
                                  template_data,
                                  is_active,
                                  version,
                                  created_by,
                                  created_on) VALUES
('db389694-ad07-45f0-9fd5-1a5dacb72bc6',
 'DMS-P',
 'WelcomeLetter4',
 'HTML',
 'Sameer',
 'donna-service-user',
 '2021-10-12',
 '[{"fieldName": "Name", "fieldType": "STRING", "isRequired": true, "defaultValue": "123"}]',
 null,
 null,
 true,
 1,
 'Anton',
 '2021-10-08');

INSERT INTO dmstemplate.template_history (audit_id,
                                          template_id,
                                          process_id,
                                          template_name,
                                          template_type,
                                          approved_by,
                                          modified_by,
                                          modified_on,
                                          template_fields,
                                          template_stamp,
                                          template_data,
                                          is_active,
                                          version,
                                          created_by,
                                          created_on )
VALUES (   '85de0ef8-486d-11ec-81d3-0242ac130003',
           'db389694-ad07-45f0-9fd5-1a5dacb72bc6',
           'DMS-P',
           'WelcomeLetter4',
           'HTML',
           'Sameer',
           'donna-service-user',
           '2021-10-12',
           '[{"fieldName": "Name", "fieldType": "STRING", "isRequired": true, "defaultValue": "123"}]',
           null,
           null,
           true,
           1,
           'Anton',
           '2021-10-08');

INSERT INTO dmstemplate.template (template_id,
                                  process_id,
                                  template_name,
                                  template_type,
                                  approved_by,
                                  modified_by,
                                  modified_on,
                                  template_fields,
                                  template_stamp,
                                  template_data,
                                  is_active,
                                  version,
                                  created_by,
                                  created_on) VALUES
('b82c65f9-5e65-4529-a0bf-3468f19b1a1e',
 'DMS-P',
 'WelcomeLetter5',
 'DOCX',
 'Sameer',
 'donna-service-user',
 '2021-10-12',
 '[{"fieldName": "Name", "fieldType": "STRING", "isRequired": true, "defaultValue": "123"}]',
 null,
 null,
 false,
 1,
 'Anton',
 '2021-10-08');

INSERT INTO dmstemplate.template_history (audit_id,
                                          template_id,
                                          process_id,
                                          template_name,
                                          template_type,
                                          approved_by,
                                          modified_by,
                                          modified_on,
                                          template_fields,
                                          template_stamp,
                                          template_data,
                                          is_active,
                                          version,
                                          created_by,
                                          created_on )
VALUES  ('4351b1ca-486d-11ec-81d3-0242ac130003',
         'b82c65f9-5e65-4529-a0bf-3468f19b1a1e',
         'DMS-P',
         'WelcomeLetter5',
         'DOCX',
         'Sameer',
         'donna-service-user',
         '2021-10-12',
         '[{"fieldName": "Name", "fieldType": "STRING", "isRequired": true, "defaultValue": "123"}]',
         null,
         null,
         false,
         1,
         'Anton',
         '2021-10-08');