update dmstemplate.template SET template_fields = '[ { "defaultValue": "", "fieldName": "firstName", "fieldType": "STRING", "isRequired": true }, { "defaultValue": "", "fieldName": "lastName", "fieldType": "STRING", "isRequired": true }, { "defaultValue": "", "fieldName": "address", "fieldType": "STRING", "isRequired": true }, { "defaultValue": "", "fieldName": "address2", "fieldType": "STRING", "isRequired": false }, { "defaultValue": "", "fieldName": "apt_suite_unit", "fieldType": "STRING", "isRequired": false }, { "defaultValue": "", "fieldName": "city", "fieldType": "STRING", "isRequired": true }, { "defaultValue": "", "fieldName": "provinceState", "fieldType": "STRING", "isRequired": true }, { "defaultValue": "", "fieldName": "postalZip", "fieldType": "STRING", "isRequired": true }, { "defaultValue": "", "fieldName": "country", "fieldType": "STRING", "isRequired": true }, { "defaultValue": "", "fieldName": "employer_name", "fieldType": "STRING", "isRequired": true }, { "defaultValue": "", "fieldName": "eligible_participation_date", "fieldType": "STRING", "isRequired": false }, { "defaultValue": "", "fieldName": "membership_form_submission_date", "fieldType": "STRING", "isRequired": false }, { "defaultValue": "", "fieldName": "possibleEarlyEnrolmentFlag", "fieldType": "BOOLEAN", "isRequired": true }, { "defaultValue": "", "fieldName": "nftMatchFlag", "fieldType": "BOOLEAN", "isRequired": true }, { "defaultValue": "", "fieldName": "activeMemberMatchFlag", "fieldType": "BOOLEAN", "isRequired": true }, { "defaultValue": "", "fieldName": "deferredMemberMatchFlag", "fieldType": "BOOLEAN", "isRequired": true } ]'
where template_id = '6ffd6a5a-198e-11ed-861d-0242ac120019';

update dmstemplate.template SET template_fields = '[ { "defaultValue": "", "fieldName": "firstName", "fieldType": "STRING", "isRequired": true }, { "defaultValue": "", "fieldName": "lastName", "fieldType": "STRING", "isRequired": true }, { "defaultValue": "", "fieldName": "address", "fieldType": "STRING", "isRequired": true }, { "defaultValue": "", "fieldName": "address2", "fieldType": "STRING", "isRequired": false }, { "defaultValue": "", "fieldName": "apt_suite_unit", "fieldType": "STRING", "isRequired": false }, { "defaultValue": "", "fieldName": "city", "fieldType": "STRING", "isRequired": true }, { "defaultValue": "", "fieldName": "provinceState", "fieldType": "STRING", "isRequired": true }, { "defaultValue": "", "fieldName": "postalZip", "fieldType": "STRING", "isRequired": true }, { "defaultValue": "", "fieldName": "country", "fieldType": "STRING", "isRequired": true }, { "defaultValue": "", "fieldName": "employer_name", "fieldType": "STRING", "isRequired": true }, { "defaultValue": "", "fieldName": "eligible_participation_date", "fieldType": "STRING", "isRequired": false }, { "defaultValue": "", "fieldName": "membership_form_submission_date", "fieldType": "STRING", "isRequired": false }, { "defaultValue": "", "fieldName": "possibleEarlyEnrolmentFlag", "fieldType": "BOOLEAN", "isRequired": true }, { "defaultValue": "", "fieldName": "nftMatchFlag", "fieldType": "BOOLEAN", "isRequired": true }, { "defaultValue": "", "fieldName": "activeMemberMatchFlag", "fieldType": "BOOLEAN", "isRequired": true }, { "defaultValue": "", "fieldName": "deferredMemberMatchFlag", "fieldType": "BOOLEAN", "isRequired": true } ]'
where template_id = '6ffd6a5a-198e-11ed-861d-0242ac120020';

update dmstemplate.template_history SET template_fields = '[ { "defaultValue": "", "fieldName": "firstName", "fieldType": "STRING", "isRequired": true }, { "defaultValue": "", "fieldName": "lastName", "fieldType": "STRING", "isRequired": true }, { "defaultValue": "", "fieldName": "address", "fieldType": "STRING", "isRequired": true }, { "defaultValue": "", "fieldName": "address2", "fieldType": "STRING", "isRequired": false }, { "defaultValue": "", "fieldName": "apt_suite_unit", "fieldType": "STRING", "isRequired": false }, { "defaultValue": "", "fieldName": "city", "fieldType": "STRING", "isRequired": true }, { "defaultValue": "", "fieldName": "provinceState", "fieldType": "STRING", "isRequired": true }, { "defaultValue": "", "fieldName": "postalZip", "fieldType": "STRING", "isRequired": true }, { "defaultValue": "", "fieldName": "country", "fieldType": "STRING", "isRequired": true }, { "defaultValue": "", "fieldName": "employer_name", "fieldType": "STRING", "isRequired": true }, { "defaultValue": "", "fieldName": "eligible_participation_date", "fieldType": "STRING", "isRequired": false }, { "defaultValue": "", "fieldName": "membership_form_submission_date", "fieldType": "STRING", "isRequired": false }, { "defaultValue": "", "fieldName": "possibleEarlyEnrolmentFlag", "fieldType": "BOOLEAN", "isRequired": true }, { "defaultValue": "", "fieldName": "nftMatchFlag", "fieldType": "BOOLEAN", "isRequired": true }, { "defaultValue": "", "fieldName": "activeMemberMatchFlag", "fieldType": "BOOLEAN", "isRequired": true }, { "defaultValue": "", "fieldName": "deferredMemberMatchFlag", "fieldType": "BOOLEAN", "isRequired": true } ]'
where audit_id = 'b059f61a-e9ff-4543-b6c8-9c4e63279634';

update dmstemplate.template_history SET template_fields = '[ { "defaultValue": "", "fieldName": "firstName", "fieldType": "STRING", "isRequired": true }, { "defaultValue": "", "fieldName": "lastName", "fieldType": "STRING", "isRequired": true }, { "defaultValue": "", "fieldName": "address", "fieldType": "STRING", "isRequired": true }, { "defaultValue": "", "fieldName": "address2", "fieldType": "STRING", "isRequired": false }, { "defaultValue": "", "fieldName": "apt_suite_unit", "fieldType": "STRING", "isRequired": false }, { "defaultValue": "", "fieldName": "city", "fieldType": "STRING", "isRequired": true }, { "defaultValue": "", "fieldName": "provinceState", "fieldType": "STRING", "isRequired": true }, { "defaultValue": "", "fieldName": "postalZip", "fieldType": "STRING", "isRequired": true }, { "defaultValue": "", "fieldName": "country", "fieldType": "STRING", "isRequired": true }, { "defaultValue": "", "fieldName": "employer_name", "fieldType": "STRING", "isRequired": true }, { "defaultValue": "", "fieldName": "eligible_participation_date", "fieldType": "STRING", "isRequired": false }, { "defaultValue": "", "fieldName": "membership_form_submission_date", "fieldType": "STRING", "isRequired": false }, { "defaultValue": "", "fieldName": "possibleEarlyEnrolmentFlag", "fieldType": "BOOLEAN", "isRequired": true }, { "defaultValue": "", "fieldName": "nftMatchFlag", "fieldType": "BOOLEAN", "isRequired": true }, { "defaultValue": "", "fieldName": "activeMemberMatchFlag", "fieldType": "BOOLEAN", "isRequired": true }, { "defaultValue": "", "fieldName": "deferredMemberMatchFlag", "fieldType": "BOOLEAN", "isRequired": true } ]'
where audit_id = 'b059f61a-e9ff-4543-b6c8-9c4e63279635';



