chaos:
  monkey:
    enabled: true
    watcher:
      component: false
      controller: false
      repository: true
      rest-controller: true
      service: false
    assaults:
      level: 5
      latencyActive: true
      exceptionsActive: true
      exception:
        type: java.lang.NullPointerException
management:
  endpoint:
    metrics:
      enabled: true
    chaosmonkey:
      enabled: true
    chaosmonkeyjmx:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,chaosmonkey

donna:
  security:
    enable: false