version: '2'
services:
  dms-template-service-app:
    image: dms-template-service:0.0.1-SNAPSHOT
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=dev
      - KAFKA_BOOTSTRAPSERVERS=kafka:9092
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dms-template-service-postgresql:5432/dms-template
    ports:
      - 9246:9246
  dms-template-service-postgresql:
    extends:
      file: baseline.yml
      service: dms-template-service-postgresql
  kafka:
    extends:
      file: kafka.yml
      service: kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
  zookeeper:
    extends:
      file: kafka.yml
      service: zookeeper
