replicas: 1
env: prod

app:
  vars:
    CREDS: /app/profile/creds.env
    _JAVA_OPTIONS: -Xms2048M -Xmx4096M
    DB_HOST: 10.16.36.55
    DB_NAME: dms-template
    DB_USER: dmstemplate_user
    DB_USER_OWNER: dmstemplate_owner
    SPRING_PROFILES_ACTIVE: prod
    SPRING_CLOUD_CONFIG_URI: http://spring-config-server.om-donna-prod.svc.cluster.local:8080
    KC_ISSUER: https://kc-prod.omers.com/auth/realms/omers
    PING_ISSUER: https://fedengine.omers.com
    PING_OPENID_ENDPOINT: https://fedengine.omers.com/idp/userinfo.openid
    KAFKA_HOST: omgnaekafb01-prod.omers.com:9091,omgnaekafb02-prod.omers.com:9091,omgnaekafb03-prod.omers.com:9091

service:
  type: ClusterIP
  sessionAffinity: ClientIP
  containerPort: &port 8080

deployment:
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "role-pensions-prod-dms-template-service"
    vault.hashicorp.com/ca-cert: /vault/tls/ca-bundle.crt
    vault.hashicorp.com/tls-secret: vault-tls-secret
    vault.hashicorp.com/agent-init-first: "true"
    vault.hashicorp.com/agent-pre-populate-only: "true"
    vault.hashicorp.com/agent-inject-secret-creds.env: "donna/donna/data/prod/dms-man-db"
    vault.hashicorp.com/secret-volume-path-creds.env: "/app/profile"
    vault.hashicorp.com/agent-inject-template-creds.env: |
      {{- with secret "donna/donna/data/prod/dms-template-db" -}}
      DB_PWD={{ .Data.data.DB_PWD }}
      DB_PWD_OWNER={{ .Data.data.DB_PWD_OWNER }}
      {{ end }}
      {{- with secret "donna/donna/data/prod/kafka" -}}
      KAFKA_KEYSTORE_PASSWORD={{ .Data.data.KAFKA_KEYSTORE_PASSWORD }}
      KAFKA_KEY_PASSWORD={{ .Data.data.KAFKA_KEY_PASSWORD }}
      KAFKA_TRUSTSTORE_PASSWORD={{ .Data.data.KAFKA_TRUSTSTORE_PASSWORD }}
      {{ end }}
    traffic.sidecar.istio.io/excludeOutboundPorts: "9091"
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8080"

  ports:
  - name: http
    containerPort: *port
    protocol: TCP
  livenessProbe:
    failureThreshold: 6
    httpGet:
      path: /actuator/health
      port: http
    periodSeconds: 10
    initialDelaySeconds: 30
  readinessProbe:
    failureThreshold: 1
    httpGet:
      path: /actuator/health
      port: http
    periodSeconds: 10
  startProbe:
    enabled: true
  startupProbe:
    failureThreshold: 6
    httpGet:
      path: /actuator/health
      port: http
    periodSeconds: 10
    initialDelaySeconds: 45

extraVolumes:
  enabled: false
  volumes:
    - name: google-cloudds-key
      enabled: false
      mountPath: /var/secrets/google/key.json
      subPath: key.json
      secretName: datastore-key

resources:
  limits:
    cpu: 1
    memory: 4096Mi
  requests:
    cpu: 600m
    memory: 2048Mi

tolerations:
- key: "dedicated"
  operator: "Equal"
  value: "donna"
  effect: "NoSchedule"

kafka:
  enabled: true
  secret: kafka-jks
